name: carbon-omarchy
description: ThinkPad X1 Hyprland. Ghostty + Omarchy Visuals. No dev bloat.
base-image: ghcr.io/ublue-os/silverblue-main
image-version: latest

modules:
  # 1. Add Repositories
  - type: script
    snippets:
      - "dnf copr enable -y ashbuk/Hyprland-Fedora"       # Stable Hyprland
      - "dnf copr enable -y cfergeau/walker"              # App Launcher
      - "dnf copr enable -y pgdev/ghostty"                # Ghostty Terminal
      - "dnf copr enable -y monkeygold/nautilus-open-any-terminal" # 'Open Terminal Here'
      - "dnf config-manager --set-enabled google-chrome"  # Chrome

  # 2. Install Packages
  - type: rpm-ostree
    install:
      # --- Hyprland Core ---
      - hyprland
      - hyprlock
      - hypridle
      - xdg-desktop-portal-hyprland
      - polkit-gnome
      
      # --- Visuals & UI ---
      - waybar
      - walker
      - swaync
      - swww
      - grim
      - slurp
      - wl-clipboard
      - google-chrome-stable
      
      # --- The "Cool" Stack ---
      - ghostty
      - starship
      - zsh
      - zsh-autosuggestions
      - zsh-syntax-highlighting

      # --- GNOME Convenience (The "Just Works" stuff) ---
      - cliphist                  # Clipboard History
      - wlsunset                  # Night Light
      - swappy                    # Screenshot Editor
      - nautilus-open-any-terminal
      - file-roller               # Archive Manager
      - loupe                     # Image Viewer
      - gnome-disk-utility
      - gnome-system-monitor
      - adw-gtk3-theme            # Theme polish
      
      # --- Fonts (Crucial for looks) ---
      - jetbrains-mono-nerd-font
      - fontawesome-fonts
      
      # --- Hardware: ThinkPad X1 & Intel ---
      - blueman
      - network-manager-applet
      - pavucontrol
      - pamixer
      - brightnessctl
      - libva-utils
      - intel-media-driver

      # --- Editors ---
      - nano-default-editor
      - fastfetch

  # 3. Intel GPU Fix
  - type: files
    files:
      - source: system/intel-env.sh
        destination: /etc/profile.d/intel-env.sh

  # 4. Flatpaks
  - type: default-flatpaks
    notify: true
    system:
      install:
        - io.github.flattool.Warehouse
        - com.spotify.Client
